/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPLlogin = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        TxtborroUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnOjo = new javax.swing.JButton();
        PsfContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPLlogin.setBackground(new java.awt.Color(0, 204, 204));

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblIniciarSesion.setText("Iniciar Sesion");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblContraseña.setText("Contraseña");

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acceso.png"))); // NOI18N

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnIniciar.setText("Iniciar");

        btnOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojo.png"))); // NOI18N

        javax.swing.GroupLayout JPLloginLayout = new javax.swing.GroupLayout(JPLlogin);
        JPLlogin.setLayout(JPLloginLayout);
        JPLloginLayout.setHorizontalGroup(
            JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLloginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtborroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPLloginLayout.createSequentialGroup()
                        .addComponent(PsfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOjo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(JPLloginLayout.createSequentialGroup()
                .addGroup(JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLloginLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblIniciarSesion))
                    .addGroup(JPLloginLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lbl)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPLloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(139, 139, 139))
        );
        JPLloginLayout.setVerticalGroup(
            JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl)
                .addGap(23, 23, 23)
                .addGroup(JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(TxtborroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(JPLloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblContraseña)
                    .addComponent(btnOjo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(PsfContraseña, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPLlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPLlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getJPLlogin() {
        return JPLlogin;
    }

    public void setJPLlogin(JPanel JPLlogin) {
        this.JPLlogin = JPLlogin;
    }

    public JPasswordField getPsfContraseña() {
        return PsfContraseña;
    }

    public void setPsfContraseña(JPasswordField PsfContraseña) {
        this.PsfContraseña = PsfContraseña;
    }

    public JTextField getTxtborroUsuario() {
        return TxtborroUsuario;
    }

    public void setTxtborroUsuario(JTextField TxtborroUsuario) {
        this.TxtborroUsuario = TxtborroUsuario;
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public void setBtnIniciar(JButton btnIniciar) {
        this.btnIniciar = btnIniciar;
    }

    public JButton getBtnOjo() {
        return btnOjo;
    }

    public void setBtnOjo(JButton btnOjo) {
        this.btnOjo = btnOjo;
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLlogin;
    private javax.swing.JPasswordField PsfContraseña;
    private javax.swing.JTextField TxtborroUsuario;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnOjo;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
