/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nuevo_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Producto
     */
    public Nuevo_Producto() {
        initComponents();
    }

    public JPanel getJPLProducto() {
        return JPLProducto;
    }

    public void setJPLProducto(JPanel JPLProducto) {
        this.JPLProducto = JPLProducto;
    }

    public JTextField getTxtNuevo_Producto() {
        return Nuevo_Producto;
    }

    public void setTxtNuevo_Producto(JTextField TxtNuevo_Producto) {
        this.Nuevo_Producto = TxtNuevo_Producto;
    }

    public JTextField getTxtborroDescripcion() {
        return TxtborroDescripcion;
    }

    public void setTxtborroDescripcion(JTextField TxtborroDescripcion) {
        this.TxtborroDescripcion = TxtborroDescripcion;
    }

    public JTextField getTxtborroImagen() {
        return TxtborroImagen;
    }

    public void setTxtborroImagen(JTextField TxtborroImagen) {
        this.TxtborroImagen = TxtborroImagen;
    }

    public JTextField getTxtborroNombre() {
        return TxtborroNombre;
    }

    public void setTxtborroNombre(JTextField TxtborroNombre) {
        this.TxtborroNombre = TxtborroNombre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Nuevo_Producto = new javax.swing.JTextField();
        JPLProducto = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        TxtborroNombre = new javax.swing.JTextField();
        TxtborroImagen = new javax.swing.JTextField();
        TxtborroDescripcion = new javax.swing.JTextField();
        lblNuevoproducto = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        Nuevo_Producto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Nuevo_Producto.setForeground(new java.awt.Color(0, 204, 255));
        Nuevo_Producto.setText("Nuevo Producto");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPLProducto.setBackground(new java.awt.Color(0, 153, 153));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombre.setText("Nombre");

        lblImagen.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblImagen.setText("Imagen");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDescripcion.setText("Descripcion");

        TxtborroImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtborroImagenActionPerformed(evt);
            }
        });

        lblNuevoproducto.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNuevoproducto.setText("Nuevo Producto");

        javax.swing.GroupLayout JPLProductoLayout = new javax.swing.GroupLayout(JPLProducto);
        JPLProducto.setLayout(JPLProductoLayout);
        JPLProductoLayout.setHorizontalGroup(
            JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLProductoLayout.createSequentialGroup()
                .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPLProductoLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(JPLProductoLayout.createSequentialGroup()
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtborroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPLProductoLayout.createSequentialGroup()
                                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(TxtborroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(JPLProductoLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(lblDescripcion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtborroDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPLProductoLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblNuevoproducto)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        JPLProductoLayout.setVerticalGroup(
            JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLProductoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNuevoproducto)
                .addGap(58, 58, 58)
                .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(TxtborroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen)
                    .addComponent(TxtborroImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(JPLProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtborroDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JPLProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JPLProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtborroImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtborroImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtborroImagenActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPLProducto;
    private javax.swing.JTextField Nuevo_Producto;
    private javax.swing.JTextField TxtborroDescripcion;
    private javax.swing.JTextField TxtborroImagen;
    private javax.swing.JTextField TxtborroNombre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNuevoproducto;
    // End of variables declaration//GEN-END:variables
}
